### ISSUE TITLE
Uncaught TypeError: Cannot read property 'id' of undefined

### ISSUE THREAD

**Issue by marothstein** [sharvil/atom-sequence-diagram#1]
## Steps to Reproduce

1. Go to Settings View (any page)
2. Use keyboard shortcut to activate Atom-Sequence-Diagram (default is `ctrl+s`)

This will trigger the error below.

My two cents: 

If there is a way to limit the contexts in which the plugin can be activated, that might solve this. It probably shouldn't bother attempting display from Settings. Then again, who the heck attempts to run this from Settings?

### System Details

**Atom**: 1.14.4 x64
**Electron**: 1.3.13
**OS**: Mac OS X 10.11.6
**Thrown From**: [sequence-diagram](https://github.com/sharvil/atom-sequence-diagram) package 0.0.2

### Stack Trace

Uncaught TypeError: Cannot read property 'id' of undefined

```
At /Users/matt/.atom/packages/sequence-diagram/src/main.js:29

TypeError: Cannot read property 'id' of undefined
    at Application.toggle_ (/packages/sequence-diagram/src/main.js:29:55)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/app.asar/src/command-registry.js:259:29)
    at /app.asar/src/command-registry.js:3:59
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:599:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:390:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeyEvent (/app.asar/src/window-event-handler.js:106:36)
    at /app.asar/src/window-event-handler.js:3:59)
```

### Commands

```
     -1:24.8.0 command-palette:toggle (input.hidden-input)
  6x -1:22.2.0 core:move-down (input.hidden-input)
     -1:18.2.0 core:confirm (input.hidden-input)
     -1:18.2.0 settings-view:view-installed-packages (input.hidden-input)
     -1:09.5.0 core:confirm (input.hidden-input)
     -0:11.5.0 sequence-diagram:toggle (div.package-detail.panels-item)
```

### Non-Core Packages

```
aligner 0.22.3 
aligner-ruby 1.5.0 
atom-gpg 0.4.0 
autocomplete-ruby 0.2.6 
build-xcodebuild 0.2.0 
color-picker 2.2.5 
compare-files 0.8.0 
emmet 2.4.3 
emmet-snippets-compatibility 1.0.6 
gist 0.3.1 
imdone-atom 2.1.21 
imdone-atom-github 0.1.11 
jenkins 0.3.5 
json-schema 0.1.15 
language-api-blueprint 1.0.2 
language-swift 0.5.0 
line-diff-details 1.5.0 
linter 1.11.23 
linter-api-blueprint 0.4.0 
linter-rails-best-practices 0.2.2 
linter-ruby 1.2.5 
linter-swagger 0.3.9 
linter-swiftlint 1.2.2 
markdown-table-formatter 2.9.0 
markdown-writer 2.6.4 
merge-conflicts 1.4.4 
minimap 4.26.8 
minimap-cursorline 0.2.0 
minimap-find-and-replace 4.5.2 
minimap-linter 1.6.0 
minimap-selection 4.4.0 
minimap-split-diff 0.3.6 
nuclide-react-native-inspector 0.0.35 
pretty-json 1.6.1 
pull-requests 0.1.0 
rails-finder 0.7.0 
rails-i18n-autocomplete 0.4.0 
rails-latest-migration 1.1.6 
rails-open-rspec 1.2.0 
rails-rspec 0.3.2 
rails-snippets 2.12.0 
rails-transporter 1.6.5 
rubocop-auto-correct 1.5.1 
ruby-navigator 0.5.0 
ruby-quick-test 0.4.0 
ruby-test 1.0.1 
ruby-test-switcher 1.2.3 
sequence-diagram 0.0.2 
spec-maker 1.0.0 
split-diff 1.2.0 
todo-show 1.11.0 
trailing-spaces 0.4.0 
xml-formatter 0.10.0 
xml-tools 0.2.1 
```

**Comment by pengzhikai** [comment]
Hi, did you resolve this issue?
